spring:
  application:
    name: company-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/company_db
    username: postgres
    password: 231504
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

